=== Vedantsahai18/MU-BE-CS-Sem-Practicals/Sem 5/Web Tech/WT/Codes/xml/games.dtd
<!ELEMENT games (game+)>
<!ATTLIST games person CDATA #REQUIRED>  
<!ELEMENT game (title, developer, year, price)>  
<!ELEMENT title (#PCDATA)>  
<!ELEMENT developer (#PCDATA)>
<!ELEMENT year (#PCDATA)>  
<!ELEMENT price (#PCDATA)>

=== Vedantsahai18/MU-BE-CS-Sem-Practicals/Sem 5/Web Tech/WT/Codes/xml/gamesdtd.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="games.xsl"?>
<!DOCTYPE games SYSTEM "games.dtd">  
<games person="me">
    <game>
        <title>Days Gone</title>
        <developer>Sony</developer>
        <year>2018</year>
        <price>2500</price>
    </game>
    <game>
        <title>FIFA 20</title>
        <developer>EA</developer>
        <year>2019</year>
        <price>3999</price>
    </game>
    <game>
        <title>PES eFootball 2020</title>
        <developer>Konami</developer>
        <year>Elvis</year>
        <price>3500</price>
    </game>
</games>
